export function supportsSpeechPractice(){return Boolean(window.SpeechRecognition||window.webkitSpeechRecognition)}
export function listenThaiOnce(){return new Promise((resolve,reject)=>{const Ctor=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Ctor){reject(new Error('Speech practice is not supported in this browser. Try Chrome or Edge.'));return}const r=new Ctor();r.lang='th-TH';r.interimResults=false;r.maxAlternatives=5;r.continuous=false;r.onresult=e=>resolve([...e.results[0]].map(x=>({transcript:x.transcript.trim(),confidence:x.confidence||0})));r.onerror=e=>reject(new Error(e.error||'Speech recognition failed'));r.start()})}
export function scoreThaiSpeech(target,alts){const r=scoreUtterance(target,alts,.92);return{ok:r.ok,heard:r.heard,score:r.score,diff:wordDiff(target,r.heard),message:r.ok?'Great speaking!':r.heard?'I heard: '+r.heard+'. Try saying '+target+' again.':'Try saying '+target+' again.'}}
export function scoreShadowLine(target,alts,threshold){const r=scoreUtterance(target,alts,threshold||.62);const pct=Math.round(r.score*100);return{ok:r.ok,heard:r.heard,score:r.score,diff:wordDiff(target,r.heard),message:r.ok?'Nice shadowing! '+pct+'% match.':r.heard?'Good try - '+pct+'% match. I heard: '+r.heard:'Try the line again.'}}
export function scoreSpokenChoice(answer,alts){const spoken=(alts&&alts[0]&&alts[0].transcript)||'';const r=scoreUtterance(answer,alts,.8);return{ok:r.ok,heard:spoken,score:r.score,message:r.ok?'Correct by voice!':'I heard: '+(spoken||'nothing')+'. Try again or tap the answer.'}}
export function wordDiff(target,heard){const t=words(target),h=words(heard);return t.map(w=>({word:w,ok:h.includes(w)}))}
export function renderDiffHtml(diff){return(diff||[]).map(x=>x.ok?'<span class="speech-ok">'+escapeHtml(x.word)+'</span>':'<span class="speech-miss">'+escapeHtml(x.word)+'</span>').join(' ')}
function scoreUtterance(target,alts,pass){const t=clean(target);let best={transcript:'',score:0};for(const a of alts||[]){const h=clean(a.transcript);const score=similarity(t,h);if(score>best.score)best={transcript:a.transcript,score}}return{ok:best.score>=pass,heard:best.transcript,score:best.score}}
function words(s){return clean(s).split(' ').filter(Boolean)}
function clean(s){return String(s||'').toLowerCase().replace(/[.,!?]/g,'').replace(/\s+/g,' ').trim()}
function similarity(a,b){if(!a&&!b)return 1;if(!a||!b)return 0;const d=lev(a,b);return Math.max(0,1-d/Math.max(a.length,b.length))}
function lev(a,b){const dp=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++){for(let j=1;j<=b.length;j++){dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1))}}return dp[a.length][b.length]}
function escapeHtml(v){return String(v).replace(/[&<>]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[ch]))}
